#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

set -e

source $OPENSHIFT_CARTRIDGE_SDK_BASH

DRUPAL_SITE_DIR=${OPENSHIFT_DATA_DIR}sites
DRUPAL_PRIVATE_DIR=${OPENSHIFT_DATA_DIR}private
DRUPAL_SETTINGS=${DRUPAL_SITE_DIR}/default/settings.php

# NOTE: possibly this won't work when it's a scaled build
if [ ! -d "${DRUPAL_SITE_DIR}/default" ]
then
  echo "No sites directory has been created, Drupal cannot be deployed"
  exit 9
fi

#
# Create a new Drupal site.  You can delete your ${OPENSHIFT_DATA_DIR}sites
# folder to run this step again.
#
if [ ! -f "${DRUPAL_SITE_DIR}/default/settings.php" ]
then

  # Set the initial password
  admin_pwd=$(generate_password)

  #
  # Automatic installation only works with mysql.
  #
  if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
  then
      echo 1>&2
      echo "Could not find mysql database. Please run:" 1>&2
      echo "rhc cartridge add mysql -a $OPENSHIFT_APP_NAME" 1>&2
      echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
      echo 1>&2
  fi

  if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
  then
      exit 5
  fi
  if [ -z "$OPENSHIFT_MYSQL_DB_PORT" ]
  then
      exit 6
  fi

  mkdir -p ${DRUPAL_SITE_DIR}/default
  mkdir -p ${DRUPAL_PRIVATE_DIR}

  pushd ${OPENSHIFT_REPO_DIR}php
  echo
  echo "Creating a new Drupal site at ${DRUPAL_SITE_DIR}/default"
  echo

fi
